"use client";

import { motion } from "framer-motion";
import { CheckCircle2, Clock, Database, DollarSign, ExternalLink, MapPin, Route, Sparkles } from "lucide-react";
import Badge from "@/components/ui/Badge";
import type { Itinerary as ItineraryType, ActivityCategory } from "@/types/itinerary";

type BadgeVariant = "default" | "success" | "warning" | "danger" | "violet" | "cyan";
const categoryColors: Record<ActivityCategory, BadgeVariant> = { adventure:"violet", culture:"cyan", food:"warning", nature:"success", photography:"violet", relaxation:"cyan", nightlife:"danger", shopping:"warning", transport:"default" };

export default function ItineraryView({itinerary}:{itinerary:ItineraryType}){
  const grounding=itinerary.grounding;
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
      <div className="glass-panel rounded-3xl p-5"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-gray-soft">Total days</p><p className="mt-3 text-3xl font-black text-white">{itinerary.totalDays}</p></div>
      <div className="glass-panel rounded-3xl p-5"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-gray-soft">Activity spend</p><p className="mt-3 text-3xl font-black text-cyan">~${itinerary.totalCost??0}</p></div>
      <div className="glass-panel rounded-3xl p-5"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-gray-soft">Mapped stops</p><p className="mt-3 text-3xl font-black text-white">{grounding?.groundedActivityCount??itinerary.days.reduce((n,d)=>n+d.activities.length,0)}</p></div>
      <div className="glass-panel rounded-3xl p-5"><p className="text-[10px] font-semibold uppercase tracking-[.17em] text-gray-soft">Data quality</p><p className="mt-3 flex items-center gap-2 text-sm font-bold text-success"><CheckCircle2 size={17}/> {grounding?.validated?"Verified":"Planned"}</p></div>
    </div>

    {grounding&&<div className="flex flex-col gap-3 rounded-3xl border border-success/15 bg-success/[.045] p-4 text-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-success/10 text-success"><Database size={18}/></div><div><p className="font-semibold text-white">Real-place grounded itinerary</p><p className="mt-0.5 text-xs text-gray-soft">{grounding.candidatePlaceCount} candidate places checked via OpenStreetMap</p></div></div><span className="text-xs text-success">{grounding.attribution}</span></div>}

    {grounding?.warnings?.length?<div className="rounded-3xl border border-warning/15 bg-warning/[.045] p-5"><p className="text-sm font-semibold text-warning">Planning notes</p><ul className="mt-2 space-y-1.5 text-xs leading-5 text-gray-soft">{grounding.warnings.map(w=><li key={w}>• {w}</li>)}</ul></div>:null}

    <div className="space-y-5">{itinerary.days.map((day,idx)=><motion.section key={day.day} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:idx*.06}} className="glass-panel overflow-hidden rounded-[30px]"><div className="flex flex-col gap-4 border-b border-white/8 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet to-cyan font-black text-white shadow-lg">{day.day}</div><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-gray-soft">Day {day.day}</p><h3 className="mt-0.5 text-lg font-bold text-white">{new Date(day.date).toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"})}</h3></div></div><div className="flex flex-wrap items-center gap-2">{day.theme&&<Badge variant="warning">{day.theme}</Badge>}{day.totalCost!==undefined&&<span className="rounded-full border border-cyan/15 bg-cyan/8 px-3 py-1 text-xs font-semibold text-cyan">~${day.totalCost}</span>}</div></div>
      {day.notes&&<div className="mx-5 mt-5 rounded-2xl border border-warning/15 bg-warning/[.045] p-4 text-sm leading-6 text-warning sm:mx-6">{day.notes}</div>}
      <div className="p-4 sm:p-6"><div className="relative space-y-3 before:absolute before:bottom-8 before:left-[21px] before:top-8 before:w-px before:bg-gradient-to-b before:from-cyan/35 before:via-violet/25 before:to-transparent">{day.activities.map((act,i)=><div key={act.id} className="relative grid gap-3 rounded-2xl border border-white/7 bg-[#080e1c]/65 p-4 transition hover:border-white/12 sm:grid-cols-[72px_1fr]"><div className="relative z-10 flex items-start gap-2 sm:block"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-cyan/15 bg-cyan/8 text-cyan"><Clock size={16}/></div><div className="mt-0 sm:mt-2"><p className="text-xs font-semibold text-white">{act.time}</p>{i<day.activities.length-1&&<p className="mt-1 text-[10px] text-slate-500">stop {i+1}</p>}</div></div><div><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h4 className="text-base font-bold text-white">{act.title}</h4>{act.placeId&&<span className="inline-flex items-center gap-1 rounded-full border border-success/20 bg-success/8 px-2 py-0.5 text-[9px] font-bold uppercase tracking-[.12em] text-success"><CheckCircle2 size={9}/> real place</span>}</div><p className="mt-2 max-w-3xl text-sm leading-6 text-gray-soft">{act.description}</p></div><Badge variant={categoryColors[act.category]??"default"}>{act.category}</Badge></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-gray-soft">{act.location&&<span className="flex items-center gap-1.5"><MapPin size={12} className="text-cyan"/>{act.location}</span>}{act.duration&&<span className="flex items-center gap-1.5"><Clock size={12}/>{act.duration}</span>}{act.estimatedCost!==undefined&&<span className="flex items-center gap-1.5"><DollarSign size={12}/>{act.costBasis==="osm-charge"?`$${act.estimatedCost}`:`~$${act.estimatedCost}`}</span>}{act.placeDistanceKm!==undefined&&<span className="flex items-center gap-1.5"><Route size={12}/>{act.placeDistanceKm} km from center</span>}{act.placeSourceUrl&&<a href={act.placeSourceUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1.5 font-medium text-cyan hover:text-white"><ExternalLink size={12}/> OSM source</a>}</div>{act.openingHours&&<div className="mt-3 inline-flex rounded-lg border border-white/7 bg-white/[.025] px-2.5 py-1.5 text-[11px] text-gray-soft"><Clock size={11} className="mr-1.5"/>{act.openingHours}</div>}</div></div>)}</div></div></motion.section>)}</div>

    <div className="flex items-start gap-2 px-2 text-[11px] leading-5 text-slate-500"><Sparkles size={12} className="mt-0.5 shrink-0"/><p>Opening hours, prices and conditions can change. TripGen uses mapped place data and planning estimates; verify important details before travel.</p></div>
  </div>
}
