import { redirect } from "next/navigation";
import Link from "next/link";
import { ArrowUpRight, Brain, CalendarDays, MapPin, Plus, Sparkles, Trophy, Zap } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Card from "@/components/ui/Card";
import Badge from "@/components/ui/Badge";
import EmptyState from "@/components/ui/EmptyState";
import ProgressBar from "@/components/ui/ProgressBar";
import AmbientBackground from "@/components/ui/AmbientBackground";
import { getAuthSession } from "@/lib/session";
import { getTripsByUser } from "@/services/itineraryService";
import { getTravelDNA, getDNABarData } from "@/services/travelDNAService";
import { getGamificationStats } from "@/services/gamificationService";
import { getPersonalityType } from "@/lib/travelDNAUtils";

export default async function DashboardPage(){
  const session=await getAuthSession(); if(!session?.user?.id) redirect("/login?callbackUrl=/dashboard");
  const [trips,dna]=await Promise.all([getTripsByUser(session.user.id),getTravelDNA(session.user.id)]);
  const stats=await getGamificationStats(session.user.id,trips); const dnaBars=dna?getDNABarData(dna).slice(0,5):[]; const personality=dna?getPersonalityType(dna):null;
  const activeTrips=trips.filter(t=>t.status==="ACTIVE"||t.status==="PLANNED"); const grounded=trips.filter(t=>t.itinerary?.grounding?.validated).length;
  return <main className="relative min-h-screen"><AmbientBackground/><Navbar/><div className="mx-auto max-w-7xl px-6 pb-20 pt-28 lg:px-8">
    <div className="flex flex-col gap-6 border-b border-white/7 pb-8 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan">Your travel workspace</p><h1 className="mt-3 text-4xl font-black tracking-[-.045em] text-white sm:text-5xl">Welcome back, {session.user.name??"Traveler"}.</h1><p className="mt-3 text-gray-soft">{activeTrips.length?`${activeTrips.length} trip${activeTrips.length===1?"":"s"} currently in motion.`:"Your next journey starts with one idea."}</p></div><Link href="/trips/new" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-violet to-cyan px-5 py-3 font-semibold text-white shadow-[0_14px_40px_rgba(124,58,237,.24)] transition hover:-translate-y-0.5"><Plus size={17}/> Plan a new trip</Link></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[
      { label: "Trips", value: stats.totalTrips, sub: "All journeys", Icon: MapPin },
      { label: "Active", value: activeTrips.length, sub: "Planned + live", Icon: CalendarDays },
      { label: "Grounded", value: grounded, sub: "Verified itineraries", Icon: Sparkles },
      { label: "Level", value: stats.level, sub: `${stats.xp} XP`, Icon: Trophy },
    ].map(({label,value,sub,Icon})=><div key={label} className="glass-panel rounded-3xl p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-[.16em] text-gray-soft">{label}</p><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/[.045] text-cyan"><Icon size={17}/></div></div><p className="mt-5 text-3xl font-black tracking-tight text-white">{String(value)}</p><p className="mt-1 text-xs text-gray-soft">{sub}</p></div>)}</div>
    <div className="mt-7 grid gap-6 lg:grid-cols-[1.6fr_.8fr]"><section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold text-white">Your trips</h2><span className="text-xs text-gray-soft">{trips.length} total</span></div>{trips.length===0?<EmptyState icon={<MapPin size={30}/>} title="No trips yet" description="Create your first grounded AI itinerary and start shaping it with the Copilot." actionLabel="Create your first trip" actionHref="/trips/new"/>:<div className="grid gap-4">{trips.map(trip=><Link key={trip.id} href={`/trips/${trip.id}`} className="group"><div className="glass-panel rounded-[26px] p-5 transition duration-300 group-hover:-translate-y-0.5 group-hover:border-cyan/20"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xl font-bold capitalize text-white">{trip.destination}</h3><Badge variant={trip.status==="ACTIVE"?"success":trip.status==="PLANNED"?"cyan":trip.status==="COMPLETED"?"violet":"default"}>{trip.status}</Badge>{trip.itinerary?.grounding?.validated&&<span className="rounded-full border border-success/20 bg-success/8 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[.12em] text-success">real-place grounded</span>}</div><div className="mt-3 flex flex-wrap gap-4 text-sm text-gray-soft"><span className="flex items-center gap-1.5"><CalendarDays size={14}/>{new Date(trip.startDate).toLocaleDateString("en-US",{month:"short",day:"numeric"})} – {new Date(trip.endDate).toLocaleDateString("en-US",{month:"short",day:"numeric"})}</span>{trip.budget&&<span>${trip.budget} {trip.currency}</span>}</div></div><div className="flex h-10 w-10 items-center justify-center rounded-2xl border border-white/8 bg-white/[.035] text-gray-soft transition group-hover:border-cyan/25 group-hover:text-cyan"><ArrowUpRight size={17}/></div></div></div></Link>)}</div>}</section>
      <aside className="space-y-5">{dna&&personality?<Card hover={false}><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-gradient-to-br from-violet/25 to-cyan/15 text-cyan"><Brain size={20}/></div><div><p className="text-xs uppercase tracking-[.15em] text-gray-soft">Travel DNA</p><h3 className="font-bold text-white">{personality.type}</h3></div></div><div className="mt-6 space-y-3">{dnaBars.map(bar=><ProgressBar key={bar.key} value={bar.value} label={bar.label}/>)}</div><Link href="/travel-dna/result" className="mt-5 flex items-center justify-between rounded-2xl border border-white/8 bg-white/[.025] px-4 py-3 text-sm text-gray-soft transition hover:border-cyan/20 hover:text-white"><span>View full profile</span><ArrowUpRight size={15}/></Link></Card>:<Card hover={false}><Brain className="text-cyan"/><h3 className="mt-4 text-lg font-bold text-white">Discover your Travel DNA</h3><p className="mt-2 text-sm leading-6 text-gray-soft">A two-minute profile makes recommendations much more personal.</p><Link href="/travel-dna/quiz" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-cyan">Take the quiz <ArrowUpRight size={14}/></Link></Card>}
      <Card hover={false}><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-warning/10 text-warning"><Trophy size={18}/></div><div><p className="text-xs text-gray-soft">Explorer level {stats.level}</p><p className="font-bold text-white">{stats.xp} XP</p></div></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><div><p className="text-xl font-black text-white">{stats.totalTrips}</p><p className="text-[10px] uppercase tracking-[.12em] text-gray-soft">Trips</p></div><div><p className="text-xl font-black text-white">{stats.destinationsVisited}</p><p className="text-[10px] uppercase tracking-[.12em] text-gray-soft">Places</p></div><div><p className="text-xl font-black text-white">{stats.badges.filter(b=>b.unlocked).length}</p><p className="text-[10px] uppercase tracking-[.12em] text-gray-soft">Badges</p></div></div></Card>
      <Card hover={false}><p className="text-xs font-semibold uppercase tracking-[.15em] text-gray-soft">Quick moves</p><div className="mt-3 grid gap-2"><Link href="/trips/new" className="flex items-center gap-2 rounded-xl px-2 py-2.5 text-sm text-gray-soft hover:bg-white/[.04] hover:text-white"><Plus size={15} className="text-cyan"/> New trip</Link><Link href="/travel-dna/quiz" className="flex items-center gap-2 rounded-xl px-2 py-2.5 text-sm text-gray-soft hover:bg-white/[.04] hover:text-white"><Sparkles size={15} className="text-cyan"/> Retake DNA quiz</Link><span className="flex items-center gap-2 rounded-xl px-2 py-2.5 text-sm text-gray-soft"><Zap size={15} className="text-cyan"/>{stats.totalTrips?"Keep exploring":"Start your journey"}</span></div></Card></aside>
    </div>
  </div><Footer/></main>
}
